name: Family Tree

on:
  # create
  workflow_dispatch:
    inputs:
      name:
        description: "Manual Trigger Github Action"
        default: "Manual"
  push:
    branches: ["main", "releases/**"]
  pull_request:
    branches: ["main"]

env:
  hasAuth: ${{ !!secrets.EXPO_TOKEN }}
  BASE_URL: "https://supabase.com/"

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn

      - name: 📦 Install dependencies
        # run: npm ci
        run: yarn install

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🧪 EAS installed
        run: eas --version

      - name: 🧪 EAS authenticated
        if: ${{ env.hasAuth == 'true' }}
        run: eas whoami

      - name: 🧪 Expo installed
        run: expo --version

      - name: 🧪 Expo authenticated
        if: ${{ env.hasAuth == 'true' }}
        run: expo whoami

  integrate:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

  staging:
    needs: [integrate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

  apk-build:
    needs: [staging]
    runs-on: ubuntu-latest
    steps:
      - name: Build APK
        run: eas build --profile preview --platform android --non-interactive --clear-cache
