name: Prepare Reusable

on:
  workflow_call:
    secrets:
      EXPO_TOKEN:
        required: true

jobs:
  build:
    runs-on: macos-latest
    env:
      JAVA_TOOL_OPTIONS: "-Xmx6g" # Increase this to Xmx4g - 4GB, adjust as needed

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK Tool
        uses: android-actions/setup-android@v3

      # - name: Install CMake and NDK
      #   run: |
      #     sdkmanager "cmake;3.30.3"  # Installing CMake 3.10.2
      #     sdkmanager "ndk;27.1.12297006"  # Installing NDK 21, known to be stable with Expo

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # - name: Prebuild Android
      #   run: yarn expo prebuild --no-install --platform android

      # - name: Clean Gradle Cache
      #   run: cd android && ./gradlew clean

      # - name: Refresh dependencies
      #   run: cd android && ./gradlew --refresh-dependencies

      # - name: Set Gradle Memory Options
      #   run: echo "org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=512m" >> ./android/gradle.properties

      # - name: Build Web App
      #   run: yarn expo export --platform web

      - name: Build Android App
        run: eas build --platform android --profile development --local --non-interactive --clear-cache --output ${{ github.workspace }}/app-release.apk

      # - name: Build IOS App
      #   run: eas build --platform ios --profile preview --local --non-interactive --clear-cache --no-wait --output=${{ github.workspace }}/app-release.apk
