name: Family Tree

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS to build on. Ubuntu is faster, MacOS supports iOS builds
        options:
          - ubuntu-latest
          - macos-latest

      platform:
        type: choice
        description: Platform to build for
        options:
          - android
          - ios
          - web

      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
          - production
  # push:
  #   branches: ["main", "releases/**", "FT-**"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  checks: write

jobs:
  # call_pre-check_workflow:
  #   uses: ./.github/workflows/pre-check-reusable.yml

  call_build_workflow:
    # needs: [call_pre-check_workflow]
    uses: ./.github/workflows/build-reusable.yml
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  call_artifact_workflow:
    needs: [call_build_workflow]
    uses: ./.github/workflows/artifact-reusable.yml
    secrets:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
