name: Family Tree

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  hasAuth: ${{ !!secrets.EXPO_TOKEN }}
  BASE_URL: "https://supabase.com/"

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: 📦 Install dependencies
        run: npm install

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          # eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 🧪 EAS installed
        run: eas --version

      - name: 🧪 EAS authenticated
        if: ${{ env.hasAuth == 'true' }}
        run: eas whoami

      - name: 🧪 Expo installed
        run: expo --version

      - name: 🧪 Expo authenticated
        if: ${{ env.hasAuth == 'true' }}
        run: expo whoami

  tsc:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Run Typescript Check
        run: npm run tsc

  lint:
    needs: [tsc]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

  prettify:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

  integrate:
    needs: [prettify]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

  staging:
    needs: [integrate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

  apk-build:
    needs: [staging]
    runs-on: ubuntu-latest
    steps:
      - name: Build APK
        run: eas build --profile preview --platform android --non-interactive --clear-cache
