name: Pre-check Reusable

on:
  workflow_call:

jobs:
  pre-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: Pre-Check Typescript, Lint And Prettier
        run: |
          yarn tsc
          yarn lint
          yarn pretty
